### PR TITLE
Binary 0.12.2

### PR DESCRIPTION
**Pull request by johansatge**
- Updated diffs
- Updated binary
- Chromium patch to prevent app crashes

### CODE REVIEW

**Comment by alexeyst** [comment]
As agreed with @johansatge this pull request will be merged once we confirm it with the App Store. Thanks again for your work @johansatge!

**Comment by ripexz** [comment]
:+1:  Any news from the App Store with this build?

**Comment by banezaklan** [comment]
@ripexz Not yet for me, the app is still in 'Waiting for Export Compliance' status, for 7 days now :-(
I guess, vacation season and all ;-)

**Comment by ripexz** [comment]
Ah cool. Yeah last update I submitted took 17 days to go through, thought it was only me! :smile:

**Comment by johansatge** [comment]
Hi,

Same here. 8 days, still waiting for validation.

**Comment by johansatge** [comment]
Hi,

the binary has been accepted by Apple :thumbsup:

**Comment by ripexz** [comment]
Great news, nice work @johansatge ! :+1:

**Comment by alexeyst** [comment]
Great work! Merging it in!

**Pull request merged**
